title: Settings
data:
  site_name: 'Brewdev Blog'
  logo: brewdev-logo.svg
  social:
    -
      id: v4Fi3VV3
      name: Twitter
      url: 'https://twitter.com/brewdev_james'
      icon: site/social-icons/twitter.svg
    -
      id: a8SX9zMP
      name: Github
      url: 'https://github.com/Brewd3v'
      icon: site/social-icons/github.svg
    -
      id: Yr42pe3v
      name: Email
      url: 'mailto:james@brewdev.co.za'
      icon: site/social-icons/email.svg
