title: Settings
data:
  site_name: 'Brewdev Blog'
  social:
    -
      id: v4Fi3VV3
      name: Twitter
      url: 'https://twitter.com/jackmcdade'
      icon: site/social-icons/twitter.svg
    -
      id: a8SX9zMP
      name: Github
      url: 'https://github.com/statamic/starter-kit-cool-writings'
      icon: site/social-icons/github.svg
    -
      id: Yr42pe3v
      name: Email
      url: 'mailto:jack@statamic.com'
      icon: site/social-icons/email.svg
